kese_limiti: 1000
itemsadder-enabled: false
oraxen-enabled: false
mysql-enabled: false
mysql:
  host: 'localhost'
  port: '3306'
  database: 'kesedatabase'
  username: 'root'
  password: 'pass'

kulce_fiyati: 5
menuler:
  kese_menu: 27
  kese_admin_menu: 27
  koy_menu: 9
  al_menu: 9
  sat_menu: 9